[InstantAutopsyInfo.Logger]
; Enables INFO-level logging (recommended)
bEnableInfo	 = true

; Enables DEBUG-level logging (developer-focused)
bEnableDebug = false

; Enables TRACE-level logging (very verbose)
bEnableTrace = false